// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://towowfyptcealmrwxvgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvd293ZnlwdGNlYWxtcnd4dmd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzE1NjYsImV4cCI6MjA2NTMwNzU2Nn0.1mxPAtSQC7pFTlTmQNn5w086JVG7gOSC8opoAjNV-mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);